{% set name = "napari-serialcellpose" %}
{% set version = "0.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/napari-serialcellpose-{{ version }}.tar.gz
  sha256: 717afe4627282dfd72a794c07527c01b9697c3c70330031e0b5a01dc600316fc

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  script_env:
    - QT_QPA_PLATFORM=offscreen

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools-scm
  run:
    - cellpose
    - magicgui
    - matplotlib-base
    - napari-aicsimageio
    - napari-skimage-regionprops
    - numpy
    - python >=3.8
    - qtpy

test:
  commands:
    - pip list
    # - pip check  # Fails due to aicsimageio and napari-aicsimageio deps
    - xvfb-run -a python -c "import napari_serialcellpose"
  requires:
    - pip
    - pyqt

about:
  home: https://pypi.org/project/napari-serialcellpose
  summary: A simple plugin to batch segment cells with cellpose
  license: BSD-3-Clause
  license_file: LICENSE
  dev_url: https://github.com/guiwitz/napari-serialcellpose

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
