{% set name = "napari-serialcellpose" %}
{% set version = "0.5.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: c801582be1ca5b09638cd3161ead858a2d682294904c54d7234e1117bd4b68dd

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  script_env:
    - QT_QPA_PLATFORM=offscreen

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools-scm
  run:
    - cellpose
    - magicgui
    - matplotlib-base
    - napari-aicsimageio
    - napari-skimage-regionprops
    - numpy
    - python >=3.8
    - qtpy

test:
  commands:
    - pip list
    # - pip check  # Fails due to aicsimageio and napari-aicsimageio deps
    - xvfb-run -a python -c "import napari_serialcellpose"
  requires:
    - pip
    - pyqt

about:
  home: https://pypi.org/project/napari-serialcellpose
  summary: A simple plugin to batch segment cells with cellpose
  license: BSD-3-Clause
  license_file: LICENSE
  dev_url: https://github.com/guiwitz/napari-serialcellpose

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
